name: Deploy Bookdown to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # this is Required for pushing to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libfontconfig1-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev
          sudo apt-get install libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - uses: actions/checkout@v4
        
      - name: Print R session info
        run: Rscript -e 'sessionInfo()'

      - name: Build the book
        run: Rscript -e 'bookdown::render_book("index.Rmd", output_dir = "_book")'

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # targeting the branch for Pages
          folder: _book           # bookdown output folder